-- 회원 삭제 테이블 추가 (데이터 분석)
CREATE TABLE user_delete (
     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email      VARCHAR(50) NOT NULL,
     category   VARCHAR(50) NOT NULL,
     message    VARCHAR(100)
);