-- 행동 로그(analytics event)를 RDB에 직접 적재하기 위한 append-only 테이블.
-- 공통 필드(event/user_id/anonymous_id/is_member/platform/occurred_at)는 컬럼으로,
-- 이벤트마다 달라지는 속성은 properties(JSON 문자열)에 담는다.
-- user_id는 비회원이면 null이며, 로그 적재가 users 존재에 묶이지 않도록 FK를 두지 않는다.
CREATE TABLE analytics_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event        VARCHAR(100) NOT NULL,
    user_id      BIGINT,
    anonymous_id VARCHAR(64),
    is_member    BOOLEAN NOT NULL,
    platform     VARCHAR(20),
    occurred_at  TIMESTAMP NOT NULL,
    properties   TEXT
);

-- 이벤트별 기간 집계(event 카운트, 전환율 등)에 사용.
CREATE INDEX idx_analytics_event_time ON analytics_events (event, occurred_at);
-- 전체 기간 스캔용.
CREATE INDEX idx_analytics_time ON analytics_events (occurred_at);
