-- 답글 지원: chat_message에 parent_message_id 추가
ALTER TABLE chat_message ADD COLUMN parent_message_id BIGINT NULL;
ALTER TABLE chat_message ADD CONSTRAINT fk_chat_message_parent
    FOREIGN KEY (parent_message_id) REFERENCES chat_message(id) ON DELETE SET NULL;

CREATE INDEX idx_chat_message_parent ON chat_message (parent_message_id);

-- 메시지별 반응 (👍 / 👎)
CREATE TABLE chat_message_reaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT NOT NULL REFERENCES chat_message(id) ON DELETE CASCADE,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    emoji       VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT uq_chat_reaction UNIQUE (message_id, user_id)
);

CREATE INDEX idx_chat_reaction_message ON chat_message_reaction (message_id);
CREATE INDEX idx_chat_reaction_user ON chat_message_reaction (user_id);
