CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub VARCHAR(255)
);

CREATE TABLE token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    token_value VARCHAR(1024),
    token_type VARCHAR(255),
    expires_at TIMESTAMP,
    revoked BOOLEAN NOT NULL,
    CONSTRAINT fk_token_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_token_value ON token (token_value);
