-- 투표 테이블 (채팅방과 1:1 매핑. 상세 필드는 Vote 담당자가 추가 예정)
CREATE TABLE vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- 투표 참여 테이블 (채팅 입장 조건. selected_option 등 상세 필드는 Vote 담당자가 추가 예정)
CREATE TABLE vote_participation (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id  BIGINT NOT NULL REFERENCES vote(id),
    user_id  BIGINT NOT NULL REFERENCES users(id),
    UNIQUE (vote_id, user_id)
);

-- 채팅 메시지 테이블
CREATE TABLE chat_message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id    BIGINT NOT NULL REFERENCES vote(id),
    sender_id  BIGINT NOT NULL REFERENCES users(id),
    content    TEXT NOT NULL,
    sent_at    TIMESTAMP NOT NULL DEFAULT now()
);

-- 채팅방별 최신 메시지 조회 및 커서 페이지네이션 최적화
CREATE INDEX idx_chat_message_vote_id ON chat_message (vote_id, sent_at DESC);

-- 사용자별 읽음 상태 추적 (안 읽은 메시지 뱃지용)
CREATE TABLE chat_room_unread (
    user_id              BIGINT NOT NULL REFERENCES users(id),
    vote_id              BIGINT NOT NULL REFERENCES vote(id),
    last_read_message_id BIGINT,                -- 마지막으로 읽은 메시지 ID
    last_read_at         TIMESTAMP,
    PRIMARY KEY (user_id, vote_id)
);

-- 채팅 메시지 발신자 정보 표시용
ALTER TABLE users ADD COLUMN nickname VARCHAR(50);
ALTER TABLE users ADD COLUMN profile_icon_url VARCHAR(512);
