CREATE TABLE vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE vote_participation (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id  BIGINT NOT NULL REFERENCES vote(id),
    user_id  BIGINT NOT NULL REFERENCES users(id),
    UNIQUE (vote_id, user_id)
);

CREATE TABLE chat_message (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id    BIGINT NOT NULL REFERENCES vote(id),
    sender_id  BIGINT NOT NULL REFERENCES users(id),
    content    TEXT NOT NULL,
    sent_at    TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_message_vote_id ON chat_message (vote_id, sent_at DESC);

CREATE TABLE chat_room_unread (
    user_id              BIGINT NOT NULL REFERENCES users(id),
    vote_id              BIGINT NOT NULL REFERENCES vote(id),
    last_read_message_id BIGINT,
    last_read_at         TIMESTAMP,
    PRIMARY KEY (user_id, vote_id)
);

ALTER TABLE users ADD COLUMN nickname VARCHAR(50);
ALTER TABLE users ADD COLUMN profile_icon_url VARCHAR(512);
