-- 유저 테이블 변경
ALTER TABLE users ADD COLUMN birth_year INT;
ALTER TABLE users ADD COLUMN gender VARCHAR(50);
ALTER TABLE users ADD COLUMN image_color VARCHAR(50);
ALTER TABLE users ADD COLUMN user_status VARCHAR(50) DEFAULT 'UNREGISTER';