-- vote 테이블 컬럼 확장 (V2에서 mock으로 만든 vote 테이블에 ALTER)
ALTER TABLE vote ADD COLUMN "type"              VARCHAR(20);
ALTER TABLE vote ADD COLUMN title               VARCHAR(100);
ALTER TABLE vote ADD COLUMN content             VARCHAR(1000);
ALTER TABLE vote ADD COLUMN thumbnail_url       VARCHAR(512);
ALTER TABLE vote ADD COLUMN image_url           VARCHAR(512);
ALTER TABLE vote ADD COLUMN status              VARCHAR(20);
ALTER TABLE vote ADD COLUMN end_at              TIMESTAMP WITH TIME ZONE;
ALTER TABLE vote ADD COLUMN created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE vote ADD COLUMN updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE vote ADD COLUMN ai_insight_headline VARCHAR(500);
ALTER TABLE vote ADD COLUMN ai_insight_body     VARCHAR(2000);

-- mock에 있던 row가 있으면 NOT NULL 제약 전 더미 채움 (운영 데이터 없음 가정)
UPDATE vote SET
    "type"        = 'GENERAL',
    title         = 'migrated',
    thumbnail_url = '',
    status        = 'ENDED',
    end_at        = now()
WHERE "type" IS NULL;

ALTER TABLE vote ALTER COLUMN "type"        SET NOT NULL;
ALTER TABLE vote ALTER COLUMN title         SET NOT NULL;
ALTER TABLE vote ALTER COLUMN thumbnail_url SET NOT NULL;
ALTER TABLE vote ALTER COLUMN status        SET NOT NULL;
ALTER TABLE vote ALTER COLUMN end_at        SET NOT NULL;

CREATE INDEX idx_vote_type_end_at   ON vote ("type", end_at DESC);
CREATE INDEX idx_vote_status_end_at ON vote (status, end_at DESC);

-- vote_option 신규
CREATE TABLE vote_option (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id   BIGINT NOT NULL REFERENCES vote(id),
    label     VARCHAR(50) NOT NULL,
    position  INT NOT NULL
);
CREATE INDEX idx_vote_option_vote_id ON vote_option (vote_id, position);

-- vote_participation 컬럼 확장
ALTER TABLE vote_participation ADD COLUMN anonymous_id VARCHAR(36);
ALTER TABLE vote_participation ADD COLUMN option_id    BIGINT;
ALTER TABLE vote_participation ADD COLUMN created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE vote_participation ADD COLUMN updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
ALTER TABLE vote_participation ALTER COLUMN user_id DROP NOT NULL;

-- mock 데이터 정리 (운영 데이터 없음 가정)
DELETE FROM vote_participation WHERE option_id IS NULL;

ALTER TABLE vote_participation ALTER COLUMN option_id SET NOT NULL;
ALTER TABLE vote_participation ADD CONSTRAINT chk_voter CHECK (
    (user_id IS NOT NULL AND anonymous_id IS NULL) OR
    (user_id IS NULL AND anonymous_id IS NOT NULL)
);
ALTER TABLE vote_participation ADD CONSTRAINT fk_vote_participation_option
    FOREIGN KEY (option_id) REFERENCES vote_option(id);

-- 기존 (vote_id, user_id) UNIQUE는 유지. anonymous_id UNIQUE 추가
ALTER TABLE vote_participation ADD CONSTRAINT uq_guest_vote UNIQUE (vote_id, anonymous_id);

CREATE INDEX idx_vp_anonymous_id ON vote_participation (anonymous_id);

-- vote_emoji_reaction 신규
CREATE TABLE vote_emoji_reaction (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id         BIGINT NOT NULL REFERENCES vote(id),
    user_id         BIGINT REFERENCES users(id),
    anonymous_id    VARCHAR(36),
    emoji           VARCHAR(20) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chk_reactor CHECK (
        (user_id IS NOT NULL AND anonymous_id IS NULL) OR
        (user_id IS NULL AND anonymous_id IS NOT NULL)
    ),
    CONSTRAINT uq_member_emoji UNIQUE (vote_id, user_id),
    CONSTRAINT uq_guest_emoji  UNIQUE (vote_id, anonymous_id)
);

-- guest_free_vote 신규
CREATE TABLE guest_free_vote (
    anonymous_id      VARCHAR(36) PRIMARY KEY,
    consumed_count    INT NOT NULL DEFAULT 0,
    last_consumed_at  TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- users 테이블에 분석용 컬럼 추가 (Insight 분석)
ALTER TABLE users ADD COLUMN gender     VARCHAR(10);
ALTER TABLE users ADD COLUMN birth_date DATE;
