-- 알림
CREATE TABLE notification (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id),
    type          VARCHAR(40) NOT NULL,
    vote_id       BIGINT REFERENCES vote(id),
    title         VARCHAR(200) NOT NULL,
    body          VARCHAR(500) NOT NULL,
    thumbnail_url VARCHAR(512),
    is_read       BOOLEAN NOT NULL DEFAULT FALSE,
    read_at       TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
CREATE INDEX idx_notification_user_created ON notification (user_id, created_at DESC);
CREATE INDEX idx_notification_user_unread  ON notification (user_id) WHERE is_read = false;

-- 알림 설정
CREATE TABLE notification_setting (
    user_id              BIGINT PRIMARY KEY REFERENCES users(id),
    push_enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    push_enabled_at      TIMESTAMP WITH TIME ZONE,
    push_disabled_at     TIMESTAMP WITH TIME ZONE,
    prompt_dismiss_count INT NOT NULL DEFAULT 0,
    last_prompt_shown_at TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- 기존 회원에 대해 NotificationSetting row 생성
INSERT INTO notification_setting (user_id)
SELECT id FROM users
ON CONFLICT (user_id) DO NOTHING;

-- Web Push 구독
CREATE TABLE push_subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    endpoint     VARCHAR(2048) NOT NULL UNIQUE,
    p256dh_key   VARCHAR(255) NOT NULL,
    auth_key     VARCHAR(255) NOT NULL,
    user_agent   VARCHAR(512),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_used_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_push_subscription_user ON push_subscription (user_id);
