-- Web Push 구독 테이블 제거 (VAPID → FCM 전환)
DROP TABLE IF EXISTS push_subscription;

-- FCM 디바이스 토큰
CREATE TABLE push_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      VARCHAR(4096) NOT NULL,
    platform   VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (user_id, token)
);

CREATE INDEX idx_push_token_user ON push_token (user_id);
