-- 홈 화면 API용 테이블

-- vote_statistics: 투표 조회수 통계
CREATE TABLE vote_statistics (
    vote_id     BIGINT PRIMARY KEY REFERENCES vote(id),
    view_count  BIGINT NOT NULL DEFAULT 0
);

-- recommended_vote: 오늘의 추천 투표
CREATE TABLE recommended_vote (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vote_id          BIGINT NOT NULL REFERENCES vote(id),
    display_order    INT NOT NULL,
    recommended_date DATE NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_recommended_vote_date ON recommended_vote (recommended_date, display_order);
