name: Create Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate version
        id: version
        uses: ./.github/actions/calculate-version

  release:
    needs: calculate-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        run: gh release create "v${{ needs.calculate-version.outputs.version }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    needs: [ calculate-version, release ]
    runs-on: ubuntu-latest

    steps:
      - name: Repository 접근
        uses: actions/checkout@v4

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker 이미지 빌드 & 푸시
        run: |
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/vs-server
          TAG=v${{ needs.calculate-version.outputs.version }}

          docker build -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: 서버 배포
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          APP_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS: 3600
          APP_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS: 1209600
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: APP_JWT_SECRET,APP_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS,APP_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS
          script: |
            curl -fsSL https://raw.githubusercontent.com/JECT-Study/JECT2-4th-Server/main/scripts/setup-docker-nginx.sh \
              | bash
            curl -fsSL https://raw.githubusercontent.com/JECT-Study/JECT2-4th-Server/main/scripts/deploy.sh \
              | bash -s ${{ secrets.DOCKER_HUB_USERNAME }}/vs-server:v${{ needs.calculate-version.outputs.version }}

  publish-api-client:
    needs: calculate-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish API Client
        uses: ./.github/actions/publish-api-client
        with:
          version: ${{ needs.calculate-version.outputs.version }}
          node-auth-token: ${{ secrets.NPM_TOKEN }}
          discord-webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          github-repository: ${{ github.repository }}
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
